
CREATE DATABASE dbBANNHACCU
GO
USE dbBANNHACCU
GO
SET DATEFORMAT dmy
go
CREATE TABLE CHUCVU
(
	ID INT IDENTITY PRIMARY KEY,
	TENCHUCVU NVARCHAR(50),
	MOTA ntext
)
CREATE TABLE TAIKHOAN
(
	ID INT IDENTITY PRIMARY KEY,
	HOVATEN NVARCHAR(50),
	EMAIL VARCHAR(50) UNIQUE,
	MATKHAU VARCHAR(50),
	IDCHUCVU INT FOREIGN KEY REFERENCES CHUCVU(ID),
	TRANGTHAI INT
)
CREATE TABLE DANHMUC
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	TENDANHMUC NVARCHAR(50),
	MOTA ntext,
	HINHANH text
)
CREATE TABLE SANPHAM
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	TENSANPHAM ntext,
	DONGIA MONEY,
	SOLUONG INT,
	HINHANH ntext,
	MOTA ntext,
	MADANHMUC INT FOREIGN KEY REFERENCES DANHMUC(ID)
		ON UPDATE CASCADE
		ON DELETE CASCADE,
		 
)
CREATE TABLE HOADON
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	IDKHACHHANG int FOREIGN KEY REFERENCES TAIKHOAN(ID)
		ON UPDATE CASCADE
		ON DELETE CASCADE,
	NGAY DATE,
	TONGTIEN MONEY,
)
CREATE TABLE CHITIETHOADON
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	IDSANPHAM INT FOREIGN KEY REFERENCES SANPHAM(ID)
		ON UPDATE CASCADE
		ON DELETE CASCADE,
	SOLUONG INT,
	DONGIA MONEY,
	IDHOADON INT FOREIGN KEY REFERENCES HOADON(ID)
		ON UPDATE CASCADE
		ON DELETE CASCADE,
)
create table CHITIETGIOHANG
(
	ID int identity primary key,
	idTaiKhoan int foreign key references TAIKHOAN(ID),
	idSanPham int foreign key references SANPHAM(ID),
	tongTien money,
	soLuong int
)